#By Exiled
name: Dotnet

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    Manghui_REFERENCES_URL: https://scp.nodefunction.net/Refs.zip
    BETA_Manghui_REFERENCES: ${{ github.workspace }}/References

jobs:

  build:

    runs-on: windows-latest
    # Prevent double running for push & pull_request events from the main repo
    if: github.event_name == 'push'

    steps:

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2

    - name: Setup Nuget
      uses: iRebbok/setup-nuget@master

    - uses: actions/checkout@v2.3.4

    - name: Get references
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri ${{ env.Manghui_REFERENCES_URL }} -OutFile ${{ github.workspace }}/References.zip
        Expand-Archive -Path References.zip -DestinationPath ${{ env.BETA_Manghui_REFERENCES }}
    - name: Build
      shell: pwsh
      run: |
        ./build.ps1 -BuildNuGet
        $File = (Get-ChildItem -Path . -Include '*.nupkg' -Recurse).Name
        Out-File -FilePath ${{ github.env }} -InputObject "PackageFile=$File" -Encoding utf-8 -Append
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Build Results
        path: bin/Release

    - name: Upload nuget package
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.PackageFile }}
        path: ${{ env.PackageFile }}
